### ISSUE TITLE
[BUG] Cannot modify header information - headers already sent

### ISSUE THREAD

**Issue by infine905** [anditv21/panel#100]
Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/mydomain.plsk.net/site/app/controllers/UtilController.php:51) 
On any pages of site, when i try preess any button or write in shoutbox end etc.

For example, i catch this error when try to write in shoutbox:

Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/mydomain.plsk.net/site/app/controllers/UtilController.php:51) in /var/www/vhosts/mydomain.plsk..net/site/index.php on line 26

Idk what this is related to and how fix it

Note: my hosting supports plesk
PHP ver - 8.2

![1234](https://user-images.githubusercontent.com/78636670/236763546-bcddf1c4-cc5c-46cb-b2b8-9022eba5697b.png)

**Comment by httpete69** [comment]
Do the sites still work?
Because then you could simply disable the error log in your webserver configuration or .htaccess files.

**Comment by infine905** [comment]
Site work but i need to update page to see new data

**Comment by infine905** [comment]
i fix error showing on page "domain.com/user/invites.php" 
by delite line 31:
"header("location: invites.php")"

**Comment by infine905** [comment]
i full fix this.
 "header("location: invites.php")" should be replaced with Util::head('Invites');

**Comment by infine905** [comment]
How i understand this error because Util::head call header() and u try to call header() again
