### ISSUE TITLE
[BUG] Pages not loading all the way and also redirections to random urls

### ISSUE THREAD

**Issue by roast247** [anditv21/panel#106]
This is what the page looks like
https://i.imgur.com/mfHto9v.png

And the following URL is what i am redirected to if i click on "Login" or "register"
https://auth/login.php

**Comment by anditv21** [comment]
Have you already checked the setup.php?
That looks to me like maybe the sub is not configured correctly.

**Comment by roast247** [comment]
Yeah, I setup the configuration how it told me when I opened the setup.php

I had all green checkmarks

**Comment by anditv21** [comment]
Please send your php error log here.

**Comment by roast247** [comment]
i figured it out, mistake on my end. Also, can this be used to license software?
