### ISSUE TITLE
[BUG] Icons not loading

### ISSUE THREAD

**Issue by Dino-log** [anditv21/panel#120]
**Describe the bug**

E.g: The '...' label shows nothing.

**To Reproduce**
Steps to reproduce the bug:
I dont know how i got it and is it just my browser

**Expected behavior**
to load the buttons

**Additional context**
in the screenshot it shows what happens
![image](https://github.com/anditv21/panel/assets/66836260/ebb25f74-e458-4a5e-b575-43b0011a65bc)

**Comment by anditv21** [comment]
Hello,
Thanks for reporting the bug.
It should be fixed in the [latest version](https://github.com/anditv21/panel/releases/latest) :)

**Comment by httpete69** [comment]
I closed the issue because there was no reply and the problem has been fixed.
