### ISSUE TITLE
[BUG] System buttons not working

### ISSUE THREAD

**Issue by Dino-log** [anditv21/panel#122]
**To Reproduce**
Steps to reproduce the bug:
click on Invite System to enable it and it wont work, same with update news

**Expected behavior**
Expected to update the news and enable the invite system

**Screenshots**
No cause there is nothing to screenshot

**Error log**
Doesnt have one, when buttons are click the page just refreshes, nothing happens

**Comment by httpete69** [comment]
Hi,
I can't tell you much about this problem either except that you should use a current php version.
Since the buttons work for me without problems I would also ask you to attach an error log here.

**Comment by Dino-log** [comment]
Fixed

**Comment by anditv21** [comment]
Uhm okay 🤝
