### ISSUE TITLE
c# form crashes when login pressed

### ISSUE THREAD

**Issue by Dino-log** [anditv21/panel#131]
Describe the bug
when i click login with any credentials i get this error 

To Reproduce
Steps to reproduce the bug:

1. download the c# example
2. put your url in
3. click login

Expected behavior
to log in

Screenshots
![5124e7fa2669b43c1942e3372d6ed520](https://github.com/anditv21/panel/assets/66836260/e678baf2-fbca-4e64-80fa-39c0c946a09b)

Additional context
also when i launched the project JObject wasnt in the "using"

**Comment by anditv21** [comment]
As you already know since you surely read the readme of the examples I don't offer any support for them.
