### ISSUE TITLE
api loader

### ISSUE THREAD

**Issue by fyta-1** [anditv21/panel#150]
Yo, are there any examples of a loader in c++ curently?

**Comment by anditv21** [comment]
> Yo, are there any examples of a loader in c++ curently?

Hey there,

Unfortunately, I don't have a fully functional C++ loader, as I primarily work with other languages.
However, I can provide you with a snippet to get started.

Please note that I haven't tested this snippet, so you might need to adjust it.
Additionally, remember that this C++ code relies on the C++ REST SDK for HTTP requests and JSON handling.

I hope it helps you. ;)

```c++
#include <iostream>
#include <string>
#include <chrono>
#include <ctime>
#include <Windows.h>
#include <winreg.h>
#include <cpprest/http_client.h>
#include <cpprest/json.h>
#include <cpprest/uri.h>
#include <cpprest/asyncrt_utils.h>

using namespace std;
using namespace web;
using namespace web::http;
using namespace web::http::client;

const string DOMAIN = "anditv.dev";
const string SUB_DIR = "/panel/";
const string API_KEY = "yes";
const string VERSION = "1";

string get_machine_guid() {
    HKEY hKey;
    LPCSTR location = "SOFTWARE\\Microsoft\\Cryptography";
    LPCSTR name = "MachineGuid";
    char machine_guid[1024];
    DWORD size = sizeof(machine_guid);
    if (RegOpenKeyExA(HKEY_LOCAL_MACHINE, location, 0, KEY_READ | KEY_WOW64_64KEY, &hKey) == ERROR_SUCCESS) {
        if (RegQueryValueExA(hKey, name, NULL, NULL, (LPBYTE)machine_guid, &size) == ERROR_SUCCESS) {
            RegCloseKey(hKey);
            return string(machine_guid);
        }
    }
    RegCloseKey(hKey);
    throw "Error getting machine GUID";
}

string send_login_request(string username, string password, string hwid) {
    string encoded_password = utility::conversions::to_base64(password);
    string encoded_hwid = utility::conversions::to_base64(hwid);

    uri_builder builder(U("https"), utility::conversions::to_string_t(DOMAIN));
    builder.append_path(utility::conversions::to_string_t(SUB_DIR + "api.php"));
    builder.append_query(U("user"), utility::conversions::to_string_t(username));
    builder.append_query(U("pass"), utility::conversions::to_string_t(encoded_password));
    builder.append_query(U("hwid"), utility::conversions::to_string_t(encoded_hwid));
    builder.append_query(U("key"), utility::conversions::to_string_t(API_KEY));

    http_client client(builder.to_uri());
    return client.request(methods::GET).get().extract_string().get();
}

int check_subscription(string sub) {
    if (sub.empty()) return 0;
    else {
        chrono::system_clock::time_point now = chrono::system_clock::now();
        time_t now_time = chrono::system_clock::to_time_t(now);
        tm current_time = *localtime(&now_time);
        tm subscription_date;
        istringstream(sub) >> get_time(&subscription_date, "%Y-%m-%d");
        return difftime(mktime(&subscription_date), mktime(&current_time)) / (60 * 60 * 24);
    }
}

int main() {
    string username, password;
    cout << "[Login] Username >> ";
    getline(cin, username);
    cout << "[Login] Password >> ";
    getline(cin, password);

    try {
        string hwid = get_machine_guid();
        string apiresult = send_login_request(username, password, hwid);
        auto json_result = json::value::parse(apiresult);

        if (json_result["status"].as_string() == "failed") {
            cout << "Username or password incorrect." << endl;
            this_thread::sleep_for(chrono::seconds(5));
            return EXIT_FAILURE;
        }

        if (json_result["Systemversion"].as_string() != VERSION) {
            cout << "You are using an outdated version." << endl;
            cout << json_result["Systemversion"].as_string() << endl;
            this_thread::sleep_for(chrono::seconds(5));
            return EXIT_FAILURE;
        }

        string system_status = json_result["Systemstatus"].as_string();
        if (system_status == "0") cout << "Status: Online" << endl;
        else if (system_status == "1") cout << "Status: Offline" << endl;
        else if (system_status == "2") cout << "Status: Maintenance" << endl;

        if (json_result["banned"].as_string() == "1") {
            cout << "Account is banned." << endl;
            this_thread::sleep_for(chrono::seconds(5));
            return EXIT_FAILURE;
        }
        else {
            cout << "Account is not banned." << endl;
        }

        cout << "You have " << check_subscription(json_result["sub"].as_string()) << " day/s sub left." << endl;

        if (hwid == json_result["hwid"].as_string()) {
            cout << "HWID does match." << endl;
        }
        else if (json_result["hwid"].is_null() || json_result["hwid"].is_empty()) {
            cout << "HWID does match." << endl;
        }
        else {
            cout << "HWID does not match." << endl;
            this_thread::sleep_for(chrono::seconds(5));
            return EXIT_FAILURE;
        }
    }
    catch (const exception& e) {
        cerr << "Error: " << e.what() << endl;
        this_thread::sleep_for(chrono::seconds(5));
        return EXIT_FAILURE;
    }

    return EXIT_SUCCESS;
}

```

**Comment by fyta-1** [comment]
Tysm ;3

**Comment by fyta-1** [comment]
There is a LOT of errors here. I'll fix them in a few hours and post them here for people to use.

**Comment by fyta-1** [comment]
#include <iostream>
#include <string>
#include <chrono>
#include <ctime>
#include <Windows.h>
#include <winreg.h>
#include <thread>
#include <iomanip>
#include <cpprest/http_client.h>
#include <cpprest/json.h>
#include <cpprest/uri.h>
#include <cpprest/containerstream.h>
#include <cpprest/producerconsumerstream.h>


using namespace std;
using namespace web;
using namespace web::http;
using namespace web::http::client;


const utility::string_t DOMENA = U("");
const utility::string_t SUB_DIR = U("/");
const utility::string_t API_KEY = U("yes");
const utility::string_t VERSION = U("1.0");

string base64_encode(const string& in) {
	DWORD encodedLength = 0;
	CryptBinaryToStringA(
		reinterpret_cast<const BYTE*>(in.data()),
		in.length(),
		CRYPT_STRING_BASE64 | CRYPT_STRING_NOCRLF,
		NULL,
		&encodedLength
	);

	string out(encodedLength, '\0');
	CryptBinaryToStringA(
		reinterpret_cast<const BYTE*>(in.data()),
		in.length(),
		CRYPT_STRING_BASE64 | CRYPT_STRING_NOCRLF,
		&out[0],
		&encodedLength
	);

	return out;
}


string send_login_request(string username, string password, string hwid) {
	string encoded_password = base64_encode(password);
	string encoded_hwid = base64_encode(hwid);

	uri_builder builder(U("http://") + DOMENA);
	builder.append_path(SUB_DIR + U("api.php"));
	builder.append_query(U("user"), utility::conversions::to_string_t(username));
	builder.append_query(U("pass"), utility::conversions::to_string_t(encoded_password));
	builder.append_query(U("hwid"), utility::conversions::to_string_t(encoded_hwid));
	builder.append_query(U("key"), utility::conversions::to_string_t(API_KEY));

	http_client client(builder.to_uri());
	std::wstring wstr = client.request(methods::GET).get().extract_string().get();
	std::string str(wstr.begin(), wstr.end());
	return str;
}




string get_machine_guid() {
	HKEY hKey;
	LPCSTR location = "SOFTWARE\\Microsoft\\Cryptography";
	LPCSTR name = "MachineGuid";
	char machine_guid[1024];
	DWORD size = sizeof(machine_guid);
	if (RegOpenKeyExA(HKEY_LOCAL_MACHINE, location, 0, KEY_READ | KEY_WOW64_64KEY, &hKey) == ERROR_SUCCESS) {
		if (RegQueryValueExA(hKey, name, NULL, NULL, (LPBYTE)machine_guid, &size) == ERROR_SUCCESS) {
			RegCloseKey(hKey);
			return string(machine_guid);
		}
	}
	RegCloseKey(hKey);
	throw runtime_error("Error getting machine GUID");
}


int check_subscription(string sub) {
	if (sub.empty()) return 0;
	else {
		chrono::system_clock::time_point now = chrono::system_clock::now();
		time_t now_time = chrono::system_clock::to_time_t(now);
		tm current_time;
		localtime_s(&current_time, &now_time);
		tm subscription_date;
		istringstream ss(sub);
		if (ss >> get_time(&subscription_date, "%Y-%m-%d")) {
			return difftime(mktime(&subscription_date), mktime(&current_time)) / (60 * 60 * 24);
		}
		else {
			throw runtime_error("Error parsing subscription date");
		}
	}
}
int main() {
	string username, password;
	cout << "[Login] Username >> ";
	getline(cin, username);
	cout << "[Login] Password >> ";
	getline(cin, password);

	try {
		string hwid = get_machine_guid();
		string apiresult = send_login_request(username, password, hwid);
		auto json_result = json::value::parse(apiresult);

		if (json_result.at(U("status")).is_string() && utility::conversions::to_utf8string(json_result.at(U("status")).as_string()) == "failed") {
			cout << "Username or password incorrect." << endl;
			std::this_thread::sleep_for(std::chrono::seconds(5));
			return EXIT_FAILURE;
		}

		if (json_result.at(U("Systemversion")).is_string() && utility::conversions::to_utf8string(json_result.at(U("Systemversion")).as_string()) != utility::conversions::to_utf8string(VERSION)) {
			cout << "You are using an outdated version." << endl;
			cout << utility::conversions::to_utf8string(json_result.at(U("Systemversion")).as_string()) << endl;
			std::this_thread::sleep_for(std::chrono::seconds(5));
			return EXIT_FAILURE;
		}

		if (json_result.at(U("banned")).is_string() && utility::conversions::to_utf8string(json_result.at(U("banned")).as_string()) == "1") {
			cout << "User is banned." << endl;
			std::this_thread::sleep_for(std::chrono::seconds(5));
			return EXIT_FAILURE;
		}
		else {
			cout << "Account is not banned." << endl;
		}

		if (json_result.at(U("frozen")).is_string() && utility::conversions::to_utf8string(json_result.at(U("frozen")).as_string()) == "1") {
			cout << "License are frozen." << endl;
		}
		else {
			cout << "Licenses are not frozen." << endl;
		}

		if (json_result.at(U("Systemstatus")).is_string()) {
			string system_status = utility::conversions::to_utf8string(json_result.at(U("Systemstatus")).as_string());
			if (system_status == "0") {
				cout << "Status: Online" << endl;
			}
			else if (system_status == "1") {
				cout << "Status: Offline" << endl;
			}
			else if (system_status == "2") {
				cout << "Status: Maintenance" << endl;
			}
		}
		else {
			cout << "System status is not available." << endl;
		}

		auto subscription_days = check_subscription(utility::conversions::to_utf8string(json_result[U("sub")].as_string()));
		std::cout << "You have " << subscription_days << " day/s sub left." << std::endl;


		auto hwid_from_json = utility::conversions::to_utf8string(json_result[U("hwid")].as_string());
		if (hwid == hwid_from_json) {
			std::cout << "HWID does match." << std::endl;
		}
		else if (json_result[U("hwid")].is_null() || json_result[U("hwid")].as_string().empty()) {
			std::cout << "HWID does match." << std::endl;
		}
		else {
			std::cout << "HWID does not match." << std::endl;
			std::this_thread::sleep_for(std::chrono::seconds(5));
			return EXIT_FAILURE;
		}
	}
	catch (const std::exception& e) {
		cerr << "Error: " << e.what() << endl;
		std::this_thread::sleep_for(std::chrono::seconds(5));
		return EXIT_FAILURE;
	}
	cout << "Press ENTER to exit...";
	cin.get();
	return EXIT_SUCCESS;
}



Linker >> Input >> Additional Dependencies >> AdvAPI32.Lib and Crypt32.Lib. 

C:\Program Files (x86)\Windows Kits\10\Lib\10.0.20348.0\um\x64\Crypt32.Lib
C:\Program Files (x86)\Windows Kits\10\Lib\10.0.20348.0\um\x64\AdvAPI32.Lib

^^ Their default location. Thank me later. You can put it as an example if you want too.

**Comment by fyta-1** [comment]
`#include <iostream>
#include <string>
#include <chrono>
#include <ctime>
#include <Windows.h>
#include <winreg.h>
#include <thread>
#include <iomanip>
#include <cpprest/http_client.h>
#include <cpprest/json.h>
#include <cpprest/uri.h>
#include <cpprest/containerstream.h>
#include <cpprest/producerconsumerstream.h>


using namespace std;
using namespace web;
using namespace web::http;
using namespace web::http::client;


const utility::string_t DOMENA = U("thlc2.xyz");
const utility::string_t SUB_DIR = U("/");
const utility::string_t API_KEY = U("yes");
const utility::string_t VERSION = U("1.1");

string base64_encode(const string& in) {
	DWORD encodedLength = 0;
	CryptBinaryToStringA(
		reinterpret_cast<const BYTE*>(in.data()),
		in.length(),
		CRYPT_STRING_BASE64 | CRYPT_STRING_NOCRLF,
		NULL,
		&encodedLength
	);

	string out(encodedLength, '\0');
	CryptBinaryToStringA(
		reinterpret_cast<const BYTE*>(in.data()),
		in.length(),
		CRYPT_STRING_BASE64 | CRYPT_STRING_NOCRLF,
		&out[0],
		&encodedLength
	);

	return out;
}


string send_login_request(string username, string password, string hwid) {
	string encoded_password = base64_encode(password);
	string encoded_hwid = base64_encode(hwid);

	uri_builder builder(U("http://") + DOMENA);
	builder.append_path(SUB_DIR + U("api.php"));
	builder.append_query(U("user"), utility::conversions::to_string_t(username));
	builder.append_query(U("pass"), utility::conversions::to_string_t(encoded_password));
	builder.append_query(U("hwid"), utility::conversions::to_string_t(encoded_hwid));
	builder.append_query(U("key"), utility::conversions::to_string_t(API_KEY));

	http_client client(builder.to_uri());
	std::wstring wstr = client.request(methods::GET).get().extract_string().get();
	std::string str(wstr.begin(), wstr.end());
	return str;
}




string get_machine_guid() {
	HKEY hKey;
	LPCSTR location = "SOFTWARE\\Microsoft\\Cryptography";
	LPCSTR name = "MachineGuid";
	char machine_guid[1024];
	DWORD size = sizeof(machine_guid);
	if (RegOpenKeyExA(HKEY_LOCAL_MACHINE, location, 0, KEY_READ | KEY_WOW64_64KEY, &hKey) == ERROR_SUCCESS) {
		if (RegQueryValueExA(hKey, name, NULL, NULL, (LPBYTE)machine_guid, &size) == ERROR_SUCCESS) {
			RegCloseKey(hKey);
			return string(machine_guid);
		}
	}
	RegCloseKey(hKey);
	throw runtime_error("Error getting machine GUID");
}


int check_subscription(string sub) {
	if (sub.empty()) return 0;
	else {
		chrono::system_clock::time_point now = chrono::system_clock::now();
		time_t now_time = chrono::system_clock::to_time_t(now);
		tm current_time;
		localtime_s(&current_time, &now_time);
		tm subscription_date;
		istringstream ss(sub);
		if (ss >> get_time(&subscription_date, "%Y-%m-%d")) {
			return difftime(mktime(&subscription_date), mktime(&current_time)) / (60 * 60 * 24);
		}
		else {
			throw runtime_error("Error parsing subscription date");
		}
	}
}
int main() {
	string username, password;
	cout << "[Login] Username >> ";
	getline(cin, username);
	cout << "[Login] Password >> ";
	getline(cin, password);

	try {
		string hwid = get_machine_guid();
		string apiresult = send_login_request(username, password, hwid);
		auto json_result = json::value::parse(apiresult);

		if (json_result.at(U("status")).is_string() && utility::conversions::to_utf8string(json_result.at(U("status")).as_string()) == "failed") {
			cout << "Username or password incorrect." << endl;
			std::this_thread::sleep_for(std::chrono::seconds(5));
			return EXIT_FAILURE;
		}

		if (json_result.at(U("Systemversion")).is_string() && utility::conversions::to_utf8string(json_result.at(U("Systemversion")).as_string()) != utility::conversions::to_utf8string(VERSION)) {
			cout << "You are using an outdated version." << endl;
			cout << utility::conversions::to_utf8string(json_result.at(U("Systemversion")).as_string()) << endl;
			std::this_thread::sleep_for(std::chrono::seconds(5));
			return EXIT_FAILURE;
		}

		if (json_result.at(U("banned")).is_string() && utility::conversions::to_utf8string(json_result.at(U("banned")).as_string()) == "1") {
			cout << "User is banned." << endl;
			std::this_thread::sleep_for(std::chrono::seconds(5));
			return EXIT_FAILURE;
		}
		else {
			cout << "Account is not banned." << endl;
		}

		if (json_result.at(U("frozen")).is_string() && utility::conversions::to_utf8string(json_result.at(U("frozen")).as_string()) == "1") {
			cout << "License are frozen." << endl;
		}
		else {
			cout << "Licenses are not frozen." << endl;
		}

		if (json_result.at(U("Systemstatus")).is_string()) {
			string system_status = utility::conversions::to_utf8string(json_result.at(U("Systemstatus")).as_string());
			if (system_status == "0") {
				cout << "Status: Online" << endl;
			}
			else if (system_status == "1") {
				cout << "Status: Offline" << endl;
			}
			else if (system_status == "2") {
				cout << "Status: Maintenance" << endl;
			}
		}
		else {
			cout << "System status is not available." << endl;
		}

		auto subscription_days = check_subscription(utility::conversions::to_utf8string(json_result[U("sub")].as_string()));
		std::cout << "You have " << subscription_days << " day/s sub left." << std::endl;


		auto hwid_from_json = utility::conversions::to_utf8string(json_result[U("hwid")].as_string());
		if (hwid == hwid_from_json) {
			std::cout << "HWID does match." << std::endl;
		}
		else if (json_result[U("hwid")].is_null() || json_result[U("hwid")].as_string().empty()) {
			std::cout << "HWID does match." << std::endl;
		}
		else {
			std::cout << "HWID does not match." << std::endl;
			std::this_thread::sleep_for(std::chrono::seconds(5));
			return EXIT_FAILURE;
		}
	}
	catch (const std::exception& e) {
		cerr << "Error: " << e.what() << endl;
		std::this_thread::sleep_for(std::chrono::seconds(5));
		return EXIT_FAILURE;
	}
	cout << "Press ENTER to exit...";
	cin.get();
	return EXIT_SUCCESS;
}`

Linker >> Input >> Additional Dependencies >> AdvAPI32.Lib and Crypt32.Lib

Make sure to have cpprest installed and that's it


Their default location is 
C:\Program Files (x86)\Windows Kits\10\Lib\10.0.20348.0\um\x64\Crypt32.Lib
C:\Program Files (x86)\Windows Kits\10\Lib\10.0.20348.0\um\x64\AdvAPI32.Lib

**Comment by fyta-1** [comment]
```
#include <iostream>
#include <string>
#include <chrono>
#include <ctime>
#include <Windows.h>
#include <winreg.h>
#include <thread>
#include <iomanip>
#include <cpprest/http_client.h>
#include <cpprest/json.h>
#include <cpprest/uri.h>
#include <cpprest/containerstream.h>
#include <cpprest/producerconsumerstream.h>


using namespace std;
using namespace web;
using namespace web::http;
using namespace web::http::client;


const utility::string_t DOMENA = U("thlc2.xyz");
const utility::string_t SUB_DIR = U("/");
const utility::string_t API_KEY = U("yes");
const utility::string_t VERSION = U("1.1");

string base64_encode(const string& in) {
	DWORD encodedLength = 0;
	CryptBinaryToStringA(
		reinterpret_cast<const BYTE*>(in.data()),
		in.length(),
		CRYPT_STRING_BASE64 | CRYPT_STRING_NOCRLF,
		NULL,
		&encodedLength
	);

	string out(encodedLength, '\0');
	CryptBinaryToStringA(
		reinterpret_cast<const BYTE*>(in.data()),
		in.length(),
		CRYPT_STRING_BASE64 | CRYPT_STRING_NOCRLF,
		&out[0],
		&encodedLength
	);

	return out;
}


string send_login_request(string username, string password, string hwid) {
	string encoded_password = base64_encode(password);
	string encoded_hwid = base64_encode(hwid);

	uri_builder builder(U("http://") + DOMENA);
	builder.append_path(SUB_DIR + U("api.php"));
	builder.append_query(U("user"), utility::conversions::to_string_t(username));
	builder.append_query(U("pass"), utility::conversions::to_string_t(encoded_password));
	builder.append_query(U("hwid"), utility::conversions::to_string_t(encoded_hwid));
	builder.append_query(U("key"), utility::conversions::to_string_t(API_KEY));

	http_client client(builder.to_uri());
	std::wstring wstr = client.request(methods::GET).get().extract_string().get();
	std::string str(wstr.begin(), wstr.end());
	return str;
}




string get_machine_guid() {
	HKEY hKey;
	LPCSTR location = "SOFTWARE\\Microsoft\\Cryptography";
	LPCSTR name = "MachineGuid";
	char machine_guid[1024];
	DWORD size = sizeof(machine_guid);
	if (RegOpenKeyExA(HKEY_LOCAL_MACHINE, location, 0, KEY_READ | KEY_WOW64_64KEY, &hKey) == ERROR_SUCCESS) {
		if (RegQueryValueExA(hKey, name, NULL, NULL, (LPBYTE)machine_guid, &size) == ERROR_SUCCESS) {
			RegCloseKey(hKey);
			return string(machine_guid);
		}
	}
	RegCloseKey(hKey);
	throw runtime_error("Error getting machine GUID");
}


int check_subscription(string sub) {
	if (sub.empty()) return 0;
	else {
		chrono::system_clock::time_point now = chrono::system_clock::now();
		time_t now_time = chrono::system_clock::to_time_t(now);
		tm current_time;
		localtime_s(&current_time, &now_time);
		tm subscription_date;
		istringstream ss(sub);
		if (ss >> get_time(&subscription_date, "%Y-%m-%d")) {
			return difftime(mktime(&subscription_date), mktime(&current_time)) / (60 * 60 * 24);
		}
		else {
			throw runtime_error("Error parsing subscription date");
		}
	}
}
int main() {
	string username, password;
	cout << "[Login] Username >> ";
	getline(cin, username);
	cout << "[Login] Password >> ";
	getline(cin, password);

	try {
		string hwid = get_machine_guid();
		string apiresult = send_login_request(username, password, hwid);
		auto json_result = json::value::parse(apiresult);

		if (json_result.at(U("status")).is_string() && utility::conversions::to_utf8string(json_result.at(U("status")).as_string()) == "failed") {
			cout << "Username or password incorrect." << endl;
			std::this_thread::sleep_for(std::chrono::seconds(5));
			return EXIT_FAILURE;
		}

		if (json_result.at(U("Systemversion")).is_string() && utility::conversions::to_utf8string(json_result.at(U("Systemversion")).as_string()) != utility::conversions::to_utf8string(VERSION)) {
			cout << "You are using an outdated version." << endl;
			cout << utility::conversions::to_utf8string(json_result.at(U("Systemversion")).as_string()) << endl;
			std::this_thread::sleep_for(std::chrono::seconds(5));
			return EXIT_FAILURE;
		}

		if (json_result.at(U("banned")).is_string() && utility::conversions::to_utf8string(json_result.at(U("banned")).as_string()) == "1") {
			cout << "User is banned." << endl;
			std::this_thread::sleep_for(std::chrono::seconds(5));
			return EXIT_FAILURE;
		}
		else {
			cout << "Account is not banned." << endl;
		}

		if (json_result.at(U("frozen")).is_string() && utility::conversions::to_utf8string(json_result.at(U("frozen")).as_string()) == "1") {
			cout << "License are frozen." << endl;
		}
		else {
			cout << "Licenses are not frozen." << endl;
		}

		if (json_result.at(U("Systemstatus")).is_string()) {
			string system_status = utility::conversions::to_utf8string(json_result.at(U("Systemstatus")).as_string());
			if (system_status == "0") {
				cout << "Status: Online" << endl;
			}
			else if (system_status == "1") {
				cout << "Status: Offline" << endl;
			}
			else if (system_status == "2") {
				cout << "Status: Maintenance" << endl;
			}
		}
		else {
			cout << "System status is not available." << endl;
		}

		auto subscription_days = check_subscription(utility::conversions::to_utf8string(json_result[U("sub")].as_string()));
		std::cout << "You have " << subscription_days << " day/s sub left." << std::endl;


		auto hwid_from_json = utility::conversions::to_utf8string(json_result[U("hwid")].as_string());
		if (hwid == hwid_from_json) {
			std::cout << "HWID does match." << std::endl;
		}
		else if (json_result[U("hwid")].is_null() || json_result[U("hwid")].as_string().empty()) {
			std::cout << "HWID does match." << std::endl;
		}
		else {
			std::cout << "HWID does not match." << std::endl;
			std::this_thread::sleep_for(std::chrono::seconds(5));
			return EXIT_FAILURE;
		}
	}
	catch (const std::exception& e) {
		cerr << "Error: " << e.what() << endl;
		std::this_thread::sleep_for(std::chrono::seconds(5));
		return EXIT_FAILURE;
	}
	cout << "Press ENTER to exit...";
	cin.get();
	return EXIT_SUCCESS;
}
```


Make sure to go to linker >> Input >> Additional Dependencies and add Crypt32.Lib and AdvAPI32.Lib


Their default location is:
C:\Program Files (x86)\Windows Kits\10\Lib\10.0.20348.0\um\x64\Crypt32.Lib
C:\Program Files (x86)\Windows Kits\10\Lib\10.0.20348.0\um\x64\AdvAPI32.Lib

You can put it as an example if you want to.

**Comment by anditv21** [comment]
Thanks a lot!
