### ISSUE TITLE
[Bug]: Cant import db into phpmyadmin

### ISSUE THREAD

**Issue by DinoSigmaRizz** [anditv21/panel#157]
### Describe the bug

it gives this error -- ------------------------------------------------------------ Table structure for table `login`--CREATE TABLE `login` (  `id` int(11) NOT NULL,  `username` varchar(255) NOT NULL,  `remembertoken` varchar(255) NOT NULL,  `ip` varchar(255) NOT NULL,  `browser` varchar(255) NOT NULL,  `os` varchar(255) NOT NULL,  `time` varchar(255) NOT NULL,  `note` varchar(255) NOT NULL,  `createdAt` date NOT NULL DEFAULT current_timestamp()) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

### Reproduction Steps

install ubuntu 22 on a vps and install cloudpanel make the website, import db into phpmyadmin

### Expected behavior

its supposed to normally import it

### Screenshots

![image](https://github.com/user-attachments/assets/0344866f-c479-416e-8a77-35730ad89c01)

### Error Log

-- ------------------------------------------------------------ Table structure for table `login`--CREATE TABLE `login` (  `id` int(11) NOT NULL,  `username` varchar(255) NOT NULL,  `remembertoken` varchar(255) NOT NULL,  `ip` varchar(255) NOT NULL,  `browser` varchar(255) NOT NULL,  `os` varchar(255) NOT NULL,  `time` varchar(255) NOT NULL,  `note` varchar(255) NOT NULL,  `createdAt` date NOT NULL DEFAULT current_timestamp()) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anditv21** [comment]
Then I recommend that you add **createAt** in the database manually with the default value **current_timestamp()**. 😉

**Comment by DinoSigmaRizz** [comment]
kk lemme try

**Comment by DinoSigmaRizz** [comment]
nah it still doesnt work... do i have some weird mysql version? | PHP version: 8.1.29 | Database client version: libmysql - mysqlnd 8.1.29 | Phpmyadmin version information: 5.2.1

**Comment by DinoSigmaRizz** [comment]
found the problem, your .sql script is trying to add in login table the createdAt as date when it should be adding it as timestamp
