### ISSUE TITLE
[Bug]:   Warning: Cannot modify header information - headers already sent

### ISSUE THREAD

**Issue by trendesetter** [anditv21/panel#165]
### Describe the bug

Can't ban anyone

### Reproduction Steps

after trying to ban someone i get this two errors

### Expected behavior

Ban

### Error Log

Warning: Cannot modify header information - headers already sent by (output started at /includes/navbar.inc.php:28) in /app/models/UsersModel.php on line 933

Warning: Cannot modify header information - headers already sent by (output started at /includes/navbar.inc.php:28) in /admin/bans.php on line 43

### Additional Context

I added ob_start(); at the beginning of the script and ob_end_flush(); at the end of the script, and now it works perfectly.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anditv21** [comment]
Hey, Thanks for the hint  unfortunately I'm not at home today.
Could you open a pull request with the fix? I would appreciate it

**Comment by trendesetter** [comment]
Hello, I've opened a pull request

**Comment by anditv21** [comment]
Thank you
