### ISSUE TITLE
[BUG] admin

### ISSUE THREAD

**Issue by dteSt4RJiRnv1TaTOlMe2go3b4FhtOWn** [anditv21/panel#64]
whilst trying to login with the account "admin", it doesnt work. when making a new account it works  i am using 000webhost

**Comment by anditv21** [comment]
Thank you for the information
I must have made a small mistake.

This should now be [fixed](https://github.com/anditv21/panel/commit/c0e6d542cb681da9c314c37610918f65488237bc).
Greetings Andreas

**Comment by dteSt4RJiRnv1TaTOlMe2go3b4FhtOWn** [comment]
im not sure if this is an issue with gamesense theme specifically, but while trying to access the front page and allat, theres no download for the loader or nothing whilst using the admin account
