### ISSUE TITLE
[BUG] latest release does not show anything

### ISSUE THREAD

**Issue by dteSt4RJiRnv1TaTOlMe2go3b4FhtOWn** [anditv21/panel#66]
with the latest release of this, its still the same
![image](https://user-images.githubusercontent.com/103281116/211141351-9f00fbae-5790-4bb7-bd3b-c5e21297eb12.png)
![image](https://user-images.githubusercontent.com/103281116/211141356-8e4a9828-4155-42c0-900d-c56c5401f882.png)
![image](https://user-images.githubusercontent.com/103281116/211141361-b231f860-daad-418d-9896-d0e21905144f.png)

**Comment by anditv21** [comment]
Strange. When I tested it everything worked. Could you manually download the files of the latest changes from github and paste them on your server?

What is in the php error log?

**Comment by dteSt4RJiRnv1TaTOlMe2go3b4FhtOWn** [comment]
yes i manually downloaded the files of the latest changes and pasted them on the server, and how do u check a php error log? sorry im kinda new to using php n allat

**Comment by anditv21** [comment]
No problem, everyone starts once.

I hope this article about the php error log can help you:

https://www.000webhost.com/forum/t/where-is-my-error-log-hosting/65859

**Comment by anditv21** [comment]
I have closed the issue 65 since these are related.

**Comment by dteSt4RJiRnv1TaTOlMe2go3b4FhtOWn** [comment]
nvm it works now

**Comment by dteSt4RJiRnv1TaTOlMe2go3b4FhtOWn** [comment]
thank u

**Comment by anditv21** [comment]
Ok I am glad to hear that.
