### ISSUE TITLE
[Feature request] make the hwid actually useful

### ISSUE THREAD

**Issue by eclipsehax1337** [anditv21/panel#67]
like in the gamesense theme, make the hwid under the profile tab and under the activate subscription and only allow the user to see this if the subscription is active. u can also add api stuff to make it so it checks if the hwid correlates with the thingy then it says in the tab "hwid true (hwid)" and if not it returns "hwid false (hwid)"

**Comment by anditv21** [comment]
Hi and thanks for your suggestion.

So you want the hwid of a user to be displayed in the profile tab when he has an active sub. 

The API should give an error if this is not correct.

Did I understand that correctly?

**Comment by dteSt4RJiRnv1TaTOlMe2go3b4FhtOWn** [comment]
yes

**Comment by dteSt4RJiRnv1TaTOlMe2go3b4FhtOWn** [comment]
also make it so u can change the hwid, forgot to mention that

**Comment by anditv21** [comment]
In the [latest release](https://github.com/anditv21/panel/releases/tag/v0.2.8) the HWID is now displayed if it is set and the user has an active subscription.

I have not implemented the check in the API.
Because it is intended that this happens in the loader.

The hardware id can already be reset by administors and supporters on the admin page.

**Comment by dteSt4RJiRnv1TaTOlMe2go3b4FhtOWn** [comment]
where would u reset the hardware id on the admin page? i dont see it

**Comment by anditv21** [comment]
In the admin dashboard
under user there is a button that looks like a micro chip. with this you can reset the hwid of your users

![opera_TsLkcRYU4a](https://user-images.githubusercontent.com/75949923/211323809-c82cf5f7-3535-42e8-8f9f-3add80831fb7.png)

**Comment by anditv21** [comment]
If you have any other questions feel free to open another issue :)
