### ISSUE TITLE
premade loader that is compatible with api?

### ISSUE THREAD

**Issue by dyrkuwu** [anditv21/panel#7]
i am making my own p2c (lmao), but i kinda suck at coding things that are using apis etc
maybe you can make a premade loader or send me a loader that is compatible with this?

**Comment by dyrkuwu** [comment]
i would greatly appreciate it

**Comment by anditv21** [comment]
Hi,
There are already premade loaders for the API:

C++: https://github.com/Jasmisek/znix-panel-loader
C#: https://github.com/spawnfdgod/znix-panel-loader
Python: https://github.com/clynt707/panel-v2-resources/blob/main/Python_Example.py
JavaScript: https://github.com/clynt707/panel-v2-resources/blob/main/JS_Example.js


Did that help you? Or are you looking for something else?

**Comment by dyrkuwu** [comment]
thank you so much, thats exactly what i was looking for
(for some reason i wasnt able to find them)
