### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by BlackDX** [anditv21/panel#70]
**Describe the bug**

**To Reproduce**
Steps to reproduce the bug:
1. Go to 'Modern Example, as admin '
2. Click on 'login tokens'
4. See error '5005'

**Comment by BlackDX** [comment]
Also when login in using modern example, you first get 500 error and need to reload, then ur logged in

**Comment by anditv21** [comment]
Thank you for your bug report.
In the latest [release ](https://github.com/anditv21/panel/releases/tag/v1.0.1)these bugs should be fixed now.

Greetings andi

**Comment by BlackDX** [comment]
@anditv21 thank you :D. I will write a new report if i find something :D
