### ISSUE TITLE
[BUG] Register and Pass change is broken.

### ISSUE THREAD

**Issue by Stealthr** [anditv21/panel#80]
**Describe the bug**
Might be on my end, but I can't register, it just says "Something went wrong"
If I change my password, in the DB it deletes the hashed password and blanks it out.

**To Reproduce**
1. Go to Admin Account Profile
2. Change password
3. Get logged out and be unable to login without manually replacing the hash.

1. Try register
2. Something went wrong

**Expected behavior**
The password changes and the account is created.

**Screenshots**
![image](https://user-images.githubusercontent.com/42773083/226087943-9edbc41f-0863-41dc-8b02-73311cebfb16.png)

**Error log**
No idea how to get it on my host

**Comment by anditv21** [comment]
Which host are you using?
Do you have access to plesk?

**Comment by anditv21** [comment]
Hello,

Thank you for reporting this issue.
Unfortunately, I could not reproduce the problem.

Regarding the registration feature, please note that usernames must be between 3 and 14 characters and may only contain letters and numbers.
Passwords must be at least 4 characters long, and the "Confirm Password" field must match the password field.

I would like to mention that a similar issue with the password change feature occurred in the past,
but it was resolved. However, it seemed to be limited to XAMPP hosting.

Which hoster are you using and do you have access to Plesk?

**Comment by Stealthr** [comment]
Fixed it by changing my Web Host, was using Epizy. 
Switched to 000webhost and works fine.
No idea why it didn't work but yeah, no access to Plesk.
