### ISSUE TITLE
[BUG] Long loading times on actions that require user input

### ISSUE THREAD

**Issue by nyquilll** [anditv21/panel#85]
very slow loading times on any event

any action on the website that requires new information or logging in is extremly slow and can take upwards of 3 minutes to complete any idea why this could be happening?

the website is running on amazon webserver 2 and currently does not have a https address

**Comment by nyquilll** [comment]
also i cannot register but im guessing this is all because of http

**Comment by anditv21** [comment]
Hi,
Thank you for letting me know about the issue.

Could you attach your PHP error log? It would help me locate the bug easily.

Previously, the slow action problem only occurred once due to incorrect setup of Config.php and DiscordConfig.php files. Have you followed the tutorial to set them up correctly?

**Comment by anditv21** [comment]
Please also note that the panel requires at least php version 8.0.

**Comment by httpete69** [comment]
> any action on the website that requires new information or logging in is extremly slow...

What exactly do you mean by "new information"?
Do you mean all features that require user input?

**Comment by nyquilll** [comment]
yes all actions that require user input are very slow

i am currently running php 8.2.3 maybe thats the problem and i should dial back the version?

i believe i have configured the php files correctly but i will redo it and see if it solves the issue

**Comment by nyquilll** [comment]
also i currently do not haver any php error logs to show

**Comment by nyquilll** [comment]
https://phlanax.cc/panel/auth/register.php
This page isn’t workingphlanax.cc is currently unable to handle this request.
HTTP ERROR 500

what could be the cause of this

**Comment by anditv21** [comment]
The PHP version appears to be fine, but without a PHP error log,
i can`t helpy you as an error 500 can have various interpretations.

**Comment by httpete69** [comment]
The location of the PHP error log can be found in either /var/log/httpd/error_log or /var/log/apache2 directory.
Another option is to modify the location of the PHP error log by using the .htaccess file.

**Comment by nyquilll** [comment]
Tried to access the logs and it said the following in Filezilla "directory /var/log/mariasb: permission denied"

"Failed to retrieve directory listing"

**Comment by anditv21** [comment]
According to the error message you are trying on "mariadb".
However, the logs are located in /var/log/httpd/error_log or /var/log/apache2.

Is there any other way to view the logs on amazon?

**Comment by nyquilll** [comment]
my apologies i forgot to check this ticket i will be trying to go into the correct folders thank you

**Comment by httpete69** [comment]
Until approximately when can we expect the server to be up and running again?

**Comment by nyquilll** [comment]
> Until approximately when can we expect the server to be up and running again?

Not exactly sure I should be able to work on it this weekend sorry

**Comment by Lauchschwert** [comment]
Hello there and sorry for just dashing in here.

Did you try hosting your website on another hosting-platform?

Also I tried hosting my own Website on a free hosting platform and since amazon webservers (and correct me if I am wrong) are free, I would also try hosting your Website on a different platform.

Sorry if I couldn't help I'm not really the web-host kind of guy.

**Comment by Lauchschwert** [comment]
And even if its paid I would try another hosting website. You can use one thats free too just to see if the problem is consistent on any hosting platform or just the one hoster

**Comment by httpete69** [comment]
To ensure optimal loading times, it is important to include webhooks in the DiscordConfig.php file.
Failure to do so may result in delays.

**Comment by httpete69** [comment]
You can reopen this issue if your server is back online and you have access to your log file.
