### ISSUE TITLE
No such file or directory in C:\xampp\htdocs\aa\app\models\UtilModel.php on line 6

### ISSUE THREAD

**Issue by lilastr0** [anditv21/panel#92]
**bug msg**

Warning: require_once(C:\xampp\htdocs\aa\app\core\Database.php): Failed to open stream: No such file or directory in C:\xampp\htdocs\aa\app\models\UtilModel.php on line 6

Fatal error: Uncaught Error: Failed opening required 'C:\xampp\htdocs\aa\app\core\Database.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\aa\app\models\UtilModel.php:6 Stack trace: #0 C:\xampp\htdocs\aa\app\controllers\UtilController.php(5): require_once() #1 C:\xampp\htdocs\aa\app\require.php(10): require_once('C:\\xampp\\htdocs...') #2 C:\xampp\htdocs\aa\index.php(2): require_once('C:\\xampp\\htdocs...') #3 {main} thrown in C:\xampp\htdocs\aa\app\models\UtilModel.php on line 6

Can you help me, idk how to fix this

**Comment by anditv21** [comment]
This is due to xampp. The panel is not designed to be hosted on a windows pc with xampp.

Try to set the php version to 8.0 or use a free hoster if you want to test the panel.

**Comment by httpete69** [comment]
> Warning: require_once(C:\xampp\htdocs\aa\app\core\Database.php): Failed to open stream: No such file or directory in C:\xampp\htdocs\aa\app\models\UtilModel.php on line 6

The error message also suggests that you did not follow the setup instructions.
