### ISSUE TITLE
Hoster issue: error connecting to database

### ISSUE THREAD

**Issue by tylerdurdenc** [anditv21/panel#95]
I decided to test this out and im having some troubles with register, after registering it just gives me "something went wrong" error
^ using infinity free

I changed hosting to 000webhost but i can't seem to connect the database because it fails with error: "Error!: SQLSTATE[HY000] [1045] ProxySQL Error: Access denied for user 'myuser'@'server' (using password: YES)"

So im guessing the issue is the hosting do you guys have any other host suggestions?

**Comment by anditv21** [comment]
Are you using infinity free or 000webhost?

Here is a list of the best free hosters:
https://www.000webhost.com/
https://www.infinityfree.net/
https://www.awardspace.com/
https://byet.host/

However, the error indicates that you have either entered the wrong username and password combination or your user does not have the necessary rights.

**Comment by tylerdurdenc** [comment]
I was using InfinityFree but for some reason it just gives me "something went wrong" error, i switched to 000webhost and i cant connect the database for some reason

everything looks fine in the images below so idk might try awardspace or byet since infinity and 000webhost its not working 
[https://i.imgur.com/5Pu0UYp.png](url)
[https://i.imgur.com/tU6MtJA.png](url)

**Comment by anditv21** [comment]
If you still use the database from infinityfree you have to change the db host.

**Comment by tylerdurdenc** [comment]
Yeah i changed the hosting name to fit correctly for each host i tried but still give me issues

**Comment by anditv21** [comment]
It would be easiest if you have the database and the webspace at the same hoster.
Otherwise you would have to enter the other IP address and the corresponding database port as host.

**Comment by Lauchschwert** [comment]
Idk if I'm drunk or not but should this be here? 
https://i.imgur.com/fVoqyub.jpeg

**Comment by anditv21** [comment]
> Idk if I'm drunk or not but should this be here? 
> 
> https://i.imgur.com/fVoqyub.jpeg

[https://stackoverflow.com/a/1773055](https://stackoverflow.com/a/1773055) 🤷‍♂️

**Comment by tylerdurdenc** [comment]
> It would be easiest if you have the database and the webspace at the same hoster. Otherwise you would have to enter the other IP address and the corresponding database port as host.

I dont know much about this hosting stuff but im hosting everything on the same place and then using database the host provides 

https://i.imgur.com/j3cdkur.png

**Comment by anditv21** [comment]
I don't see much on the screenshots and I don't know if you changed anything afterwards but when I compare the config and your data they don't match.
Which is also confirmed by the error message..

> "Error!: SQLSTATE[HY000] [1045] ProxySQL Error: Access denied for user 'myuser'@'server' (using password: YES)"

![j3cdkur](https://user-images.githubusercontent.com/75949923/234837721-58d463f5-4956-4ed2-ad25-64f2a9aa327f.png)
![tU6MtJA](https://user-images.githubusercontent.com/75949923/234837722-db18e786-fcd0-4c96-88fb-69b7092ab1d6.png)

**Comment by anditv21** [comment]
The warning after registration is most likely because no connection to the database can be established.

**Comment by tylerdurdenc** [comment]
> The warning after registration is most likely because no connection to the database can be established.

I recorded this video demonstrating what im doing:
https://streamable.com/jbxusr

About the config data everything seems fine and still not working

**Comment by tylerdurdenc** [comment]
Oh dang 3 errors thats bad

https://i.imgur.com/7GWLJ4L.png

**Comment by httpete69** [comment]
Here are a few of the most popular hosters:
https://zap-hosting.com/en/shop/product/webspace/
https://www.ionos.com/hosting/web-hosting
https://www.digitalocean.com/solutions/website-hosting

**Comment by anditv21** [comment]
Is everything working now how it should?

**Comment by tylerdurdenc** [comment]
> Is everything working now how it should?

Yes i changed host now it works
